<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="wheelchair">
  <xacro:property name="chair_width" value="0.643" /> <!-- From front wheel right joint to front wheel left joint -->
  <xacro:property name="chair_length" value="0.812" /> <!-- From front wheel joint to back wheel joint -->
  <xacro:property name="chair_height" value="1.191" /> <!-- From front wheel joint to head rest -->
  <xacro:property name="chair_weight" value="10.0" />
  

  <xacro:property name="legs_width" value="0.4064" />
  <xacro:property name="legs_length" value="0.4064" />
  <xacro:property name="legs_height" value="0.4064" />
  <xacro:property name="legs_weight" value="2.0" />

  <xacro:property name="main_wheel_length" value="0.065" />
  <xacro:property name="main_wheel_radius" value=".165" />
  <xacro:property name="main_wheel_weight" value="2.0" />

  <xacro:property name="small_wheel_radius" value=".089" />
  <xacro:property name="small_wheel_length" value=".05" />
  <xacro:property name="small_wheel_weight" value="1.0" />

  <xacro:macro name="box_intertia" params="height length width weight" >
    <inertia ixx="${1/12 * weight * (height + length)}" ixy="0" ixz="0" iyy="${1/12 * weight * (width + length)}" iyz="0" izz="${1/12 * weight * (width + height)}" />
  </xacro:macro>

  <xacro:macro name="cylinder_intertia" params="length radius weight" >
    <inertia ixx="${1/12 * weight * (3 * radius * radius + length * length)}" ixy="0" ixz="0" iyy="${1/12 * weight * (3 * radius*radius + length*length)}" iyz="0" izz="${1/2 * weight * radius*radius}" />
  </xacro:macro>



  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chair_width} ${chair_length} ${chair_height}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chair_width} ${chair_length} ${chair_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${chair_weight}"/>
      <xacro:box_intertia height="${chair_height}" length="${chair_length}" width="${chair_width}" weight="${chair_weight}" />
    </inertial>
  </link>

<!--Legs -->
  <link name="legs">
    <visual>
      <geometry>
        <box size="${legs_width} ${legs_length} ${legs_height}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${legs_width} ${legs_length} ${legs_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${legs_weight}"/>
      <xacro:box_intertia height="${legs_height}" length="${legs_length}" width="${legs_width}" weight="${legs_weight}" />
    </inertial>
  </link>

    <joint name="legs_joint" type="fixed">
    <axis xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="legs"/>
    <origin rpy="0 0 0" xyz="0 -${chair_length/2 + 0.4064/2} -${chair_height/2 - 0.4064/2}"/> <!--chair_height/4 + chair_height/8 because this is relative to the center of the bar -->
  </joint>

<!--Right Bar -->
  <link name="right_bar">
    <visual>
      <geometry>
        <box size="${chair_width/4} ${chair_length + chair_length/4} ${chair_height/8}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chair_width/4} ${chair_length} ${chair_height/8}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>

  <joint name="right_bar_joint" type="fixed">
    <axis xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="right_bar"/>
    <origin rpy="0 0 0" xyz="${chair_width/2} 0.0 -${chair_height/4 + chair_height/8}"/> <!--chair_height/4 + chair_height/8 because this is relative to the center of the bar -->
  </joint>

<!--Left Bar -->

  <link name="left_bar">
    <visual>
      <geometry>
        <box size="${chair_width/4} ${chair_length + chair_length/4} ${chair_height/8}"/>
      </geometry>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chair_width/4} ${chair_length} ${chair_height/8}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>

  <joint name="left_bar_joint" type="fixed">
    <axis xyz="0 0 0"/>
    <parent link="base_link"/>
    <child link="left_bar"/>
    <origin rpy="0 0 0" xyz="-${chair_width/2} 0.0 -${chair_height/4 + chair_height/8}"/> <!--chair_height/4 + chair_height/8 because this is relative to the center of the bar -->
  </joint>


<!--Main Wheels -->
  <joint name="right_main_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="right_bar"/>
    <child link="right_main_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0.0 0.0 -${chair_height/8-0.076}"/>
  </joint>

  <link name="right_main_wheel">
    <visual>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${main_wheel_weight}"/>
      <xacro:cylinder_intertia length="${main_wheel_length}" radius="${main_wheel_radius}" weight="${main_wheel_weight}" />
    </inertial>
  </link>

  <joint name="left_main_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="left_bar"/>
    <child link="left_main_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0.0 0.0 -${chair_height/8-0.076}"/>
  </joint>

  <link name="left_main_wheel">
    <visual>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${main_wheel_length}" radius="${main_wheel_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${main_wheel_weight}"/>
      <xacro:cylinder_intertia length="${main_wheel_length}" radius="${main_wheel_radius}" weight="${main_wheel_weight}" />
    </inertial>
  </link>


<!--Laser Scanners -->

  <link name="right_scanner">
    <visual>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.1"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1e-5" />
      <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
  </link>

  <joint name="right_scanner_joint" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="${0.05/2} -${chair_length/2 - 0.05/2 + chair_length/8} ${chair_height/16 + 0.05}" rpy="0 0 0"/>
    <parent link="right_bar"/>
    <child link="right_scanner"/>
  </joint>

  <link name="left_scanner">
    <visual>
      <origin xyz="0.0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 0.1"/>
      </geometry>
    </visual>
    <collision>
      <geometry>
        <box size="0.05 0.05 0.1"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1e-5" />
      <inertia ixx="1e-3" ixy="0" ixz="0" iyy="1e-3" iyz="0" izz="1e-3" />
    </inertial>
  </link>

  <joint name="left_scanner_joint" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="-${0.05/2} -${chair_length/2 - 0.05/2 + chair_length/8} ${chair_height/16 + 0.05}" rpy="0 0 -3.14"/>
    <parent link="left_bar"/>
    <child link="left_scanner"/>
  </joint>



<!--Front Wheels -->

  <link name="front_right_swivel">
    <visual>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>


   <joint name="front_right_swivel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="right_bar"/>
    <child link="front_right_swivel"/>
    <origin rpy="0 0 0" xyz="0.0 -${chair_length/2} -${chair_height/8}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>


  <joint name="front_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="front_right_swivel"/>
    <child link="front_right_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 0.065 0"/>
    <dynamics damping="1.0" friction="1.5" />
  </joint>

  <link name="front_right_wheel">
    <visual>
      <geometry>
        <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${small_wheel_length}" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>100.0</mu>
            <mu2>100.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>

  <link name="front_left_swivel">
    <visual>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>


   <joint name="front_left_swivel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="left_bar"/>
    <child link="front_left_swivel"/>
    <origin rpy="0 0 0" xyz="0.0 -${chair_length/2} -${chair_height/8}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>


  <joint name="front_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="front_left_swivel"/>
    <child link="front_left_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 0.065 0"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="front_left_wheel">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>100.0</mu>
            <mu2>100.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>
  
<!--Rear Wheels -->

  <link name="rear_right_swivel">
    <visual>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>


   <joint name="rear_right_swivel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="right_bar"/>
    <child link="rear_right_swivel"/>
    <origin rpy="0 0 0" xyz="0.0 ${chair_length/2} -${chair_height/8}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>


  <joint name="rear_right_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="rear_right_swivel"/>
    <child link="rear_right_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 0.065 0"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="rear_right_wheel">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>100.0</mu>
            <mu2>100.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>

  <link name="rear_left_swivel">
    <visual>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.065" radius="0.01"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>


   <joint name="rear_left_swivel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="left_bar"/>
    <child link="rear_left_swivel"/>
    <origin rpy="0 0 0" xyz="0.0 ${chair_length/2} -${chair_height/8}"/>
    <dynamics damping="0.0" friction="0.5" />
  </joint>


  <joint name="rear_left_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="rear_left_swivel"/>
    <child link="rear_left_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 0.065 0"/>
    <dynamics damping="0" friction="0.5" />
  </joint>

  <link name="rear_left_wheel">
    <visual>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder length="0.05" radius="${small_wheel_radius}"/>
      </geometry>
      <surface>
        <friction>
          <ode>
            <mu>100.0</mu>
            <mu2>100.0</mu2>
          </ode>
        </friction>
      </surface>
    </collision>
    <inertial>
      <mass value="${small_wheel_weight}"/>
      <xacro:cylinder_intertia length="${small_wheel_length}" radius="${small_wheel_radius}" weight="${small_wheel_weight}" />
    </inertial>
  </link>






<gazebo>
  <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <alwaysOn>true</alwaysOn>
    <updateRate>50</updateRate>
    <leftJoint>right_main_wheel_joint</leftJoint>
    <rightJoint>left_main_wheel_joint</rightJoint>
    <wheelSeparation>0.5380</wheelSeparation>
    <wheelDiameter>${main_wheel_radius}</wheelDiameter>
    <torque>20</torque>
    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <robotBaseFrame>base_footprint</robotBaseFrame>
  </plugin>
</gazebo>


<gazebo reference="right_scanner">
    <sensor type="gpu_ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-2.35619449</min_angle>
            <max_angle>2.35619449</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
        <topicName>/wheelchair/laser/scan</topicName>
        <frameName>right_scanner</frameName>
      </plugin>
    </sensor>
  </gazebo>

<gazebo reference="left_scanner">
    <sensor type="gpu_ray" name="head_hokuyo_sensor2">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-2.35619449</min_angle>
            <max_angle>2.35619449</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.10</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>

          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller2" filename="libgazebo_ros_gpu_laser.so">
        <topicName>/wheelchair/laser2/scan</topicName>
        <frameName>left_scanner</frameName>
      </plugin>
    </sensor>
  </gazebo>

</robot>
  <!--
  <link name="right_leg">
    <visual>
      <geometry>
        <box size="0.6 .2 .1"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 -0.3"/>
      <material name="white">
        <color rgba="1 1 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.6 .2 .1"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 -0.3"/>
    </collision>
    <inertial>
      <mass value="0.6"/>
      <inertia ixx="1e-3" ixy="1e-3" ixz="1e-3" iyy="1e-3" iyz="1e-3" izz="1e-3"/>
    </inertial>
  </link>

  <joint name="base_to_right_leg" type="fixed">
    <parent link="base_link"/>
    <child link="right_leg"/>
    <origin xyz="0.22 0 .25"/>
  </joint>

  <link name="right_base">
    <visual>
      <geometry>
        <box size=".1 0.4 .1"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="right_base_joint" type="fixed">
    <parent link="right_leg"/>
    <child link="right_base"/>
    <origin xyz="0 0 -0.6"/>
  </joint>

  <link name="right_front_wheel">
    <visual>
      <geometry>
        <cylinder length=".1" radius="0.035"/>
      </geometry>
      <material name="white">
        <color rgba="0 0 0 1"/>
      </material>
    </visual>
  </link>

  <joint name="right_front_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="right_base"/>
    <child link="right_front_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 0.133333333333 -0.085"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <link name="right_back_wheel">
    <visual>
      <geometry>
        <cylinder length=".1" radius="0.035"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="right_back_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="right_base"/>
    <child link="right_back_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 -0.133333333333 -0.085"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <link name="left_leg">
    <visual>
      <geometry>
        <box size="0.6 .2 .1"/>
      </geometry>
      <origin rpy="0 1.57075 0" xyz="0 0 -0.3"/>
      <material name="white"/>
    </visual>
  </link>

  <joint name="base_to_left_leg" type="fixed">
    <parent link="base_link"/>
    <child link="left_leg"/>
    <origin xyz="-0.22 0 .25"/>
  </joint>

  <link name="left_base">
    <visual>
      <geometry>
        <box size=".1 0.4 .1"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="left_base_joint" type="fixed">
    <parent link="left_leg"/>
    <child link="left_base"/>
    <origin xyz="0 0 -0.6"/>
  </joint>

  <link name="left_front_wheel">
    <visual>
      <geometry>
        <cylinder length=".1" radius="0.035"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="left_front_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="left_base"/>
    <child link="left_front_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 0.133333333333 -0.085"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>

  <link name="left_back_wheel">
    <visual>
      <geometry>
        <cylinder length=".1" radius="0.035"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="left_back_wheel_joint" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="left_base"/>
    <child link="left_back_wheel"/>
    <origin rpy="0 1.57075 0" xyz="0 -0.133333333333 -0.085"/>
    <limit effort="100" velocity="100"/>
    <joint_properties damping="0.0" friction="0.0"/>
  </joint>
  <joint name="gripper_extension" type="prismatic">
    <parent link="base_link"/>
    <child link="gripper_pole"/>
    <limit effort="1000.0" lower="-0.38" upper="0" velocity="0.5"/>
    <origin rpy="0 0 1.57075" xyz="0 0.19 .2"/>
  </joint>

  <link name="gripper_pole">
    <visual>
      <geometry>
        <cylinder length="0.2" radius=".01"/>
      </geometry>
      <origin rpy="0 1.57075 0 " xyz="0.1 0 0"/>
      <material name="Gray">
        <color rgba=".7 .7 .7 1"/>
      </material>
    </visual>
  </link>

  <joint name="left_gripper_joint" type="revolute">
    <axis xyz="0 0 1"/>
    <limit effort="1000.0" lower="0.0" upper="0.548" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0.2 0.01 0"/>
    <parent link="gripper_pole"/>
    <child link="left_gripper"/>
  </joint>

  <link name="left_gripper">
    <visual>
      <origin rpy="0.0 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://pr2_description/meshes/gripper_v0/l_finger.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="left_tip_joint" type="fixed">
    <parent link="left_gripper"/>
    <child link="left_tip"/>
  </joint>

  <link name="left_tip">
    <visual>
      <origin rpy="0.0 0 0" xyz="0.09137 0.00495 0"/>
      <geometry>
        <mesh filename="package://pr2_description/meshes/gripper_v0/l_finger_tip.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="right_gripper_joint" type="revolute">
    <axis xyz="0 0 -1"/>
    <limit effort="1000.0" lower="0.0" upper="0.548" velocity="0.5"/>
    <origin rpy="0 0 0" xyz="0.2 -0.01 0"/>
    <parent link="gripper_pole"/>
    <child link="right_gripper"/>
  </joint>

  <link name="right_gripper">
    <visual>
      <origin rpy="-3.1415 0 0" xyz="0 0 0"/>
      <geometry>
        <mesh filename="package://pr2_description/meshes/gripper_v0/l_finger.dae"/>
      </geometry>
    </visual>
  </link>

  <joint name="right_tip_joint" type="fixed">
    <parent link="right_gripper"/>
    <child link="right_tip"/>
  </joint>

  <link name="right_tip">
    <visual>
      <origin rpy="-3.1415 0 0" xyz="0.09137 0.00495 0"/>
      <geometry>
        <mesh filename="package://pr2_description/meshes/gripper_v0/l_finger_tip.dae"/>
      </geometry>
    </visual>
  </link>

  <link name="head">
    <visual>
      <geometry>
        <sphere radius="0.2"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <joint name="head_swivel" type="continuous">
    <parent link="base_link"/>
    <child link="head"/>
    <axis xyz="0 0 1"/>
    <origin xyz="0 0 0.3"/>
  </joint>

  <link name="box">
    <visual>
      <geometry>
        <box size=".08 .08 .08"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <joint name="tobox" type="fixed">
    <parent link="head"/>
    <child link="box"/>
    <origin xyz="0 0.1414 0.1414"/>
  </joint>

-->
